### PR TITLE
upgrade logr dependency

### PR DESCRIPTION
**Pull request by Diaphteiros**
**What this PR does / why we need it**:
Due to a breaking change with logr `v1.0.0`, projects which depend on this one can only upgrade their logr version if it is upgraded in this project too.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/hold
Requires a release of component-spec containing https://github.com/gardener/component-spec/pull/79 first.

**Release note**:

```breaking developer
Upgraded logr to `v1.2.3`
```

### CODE REVIEW

**Comment by Diaphteiros** [comment]
/hold
I have a failing test locally, which needs to be investigated first.

**Comment by Diaphteiros** [comment]
/unhold
It's a problem with a file that is created during testing and not always properly cleaned up, which can create problems on subsequent test runs. Not related to the changes of this PR.

**Review by jschicktanz — APPROVED** [review]

**Review by jschicktanz — APPROVED** [review]

**Pull request merged**
